"""
Django settings for screecher project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

from os import path, scandir, listdir
from re import split

# Build paths inside the project like this: path.join(BASE_DIR, ...)

BASE_DIR = path.dirname(path.dirname(path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@4_s-kj9hu_66n++ou!%!tt@!nz+o3lc31#=l5*v+h+)yhoyvp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

APP_NAMES = [d.name for d in scandir(BASE_DIR) if d.is_dir() and 'apps.py' in listdir(path.join(BASE_DIR, d.name))]


def to_camel_case(string):
    return ''.join(substring.capitalize() for substring in split('([^a-zA-Z0-9])', string) if substring.isalnum())


# dynamically add other installed apps
for app in APP_NAMES:
    INSTALLED_APPS.append(f"{app}.apps.{to_camel_case(app)}Config")

APP_URLS = {}

# dynamically add app url paths
for app in APP_NAMES:
    if app != 'analytics':
        APP_URLS[app] = f"{app}/"

SESSION_COOKIE_DOMAIN = 'team13.screecher.de'
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True

HOST_MIDDLEWARE_URLCONF_MAP = {
    'team13': 'screecher.urls',
    'analytics': 'analytics.urls',
}

MIDDLEWARE = [
    'screecher.middleware.ErrorPageMiddleware',
    'screecher.middleware.MultiHostMiddleware',
    'screecher.middleware.TimezoneMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'screecher.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [path.join(BASE_DIR, 'screecher/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'screecher.context_processors.app_names',
                'screecher.context_processors.profile_pictures'
            ],
        },
    },
]

WSGI_APPLICATION = 'screecher.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'screecher',
        'USER': 'screecher',
        'PASSWORD': 'fbe573d0f207616eb1c8798c9b2fb7a2',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [path.join(BASE_DIR, 'screecher/static')]

MEDIA_URL = '/media/'

MEDIA_ROOT = path.join(BASE_DIR, 'screecher/media')
